format = """
$directory \
$git_branch \
$git_status \
$fill \
$c \
$elixir \
$elm \
$golang \
$haskell \
$java \
$julia \
$nodejs \
$nim \
$rust \
$scala \
$python\n  \
[󱞪 ](fg:iris)
"""

# Use the color palette
palette = "dracula"

# Define Dracula color palette
[palettes.dracula]
background = "#282a36"
current_line = "#44475a"
foreground = "#f8f8f2"
comment = "#6272a4"
cyan = "#8be9fd"
green = "#50fa7b"
orange = "#ffb86c"
pink = "#ff79c6"
purple = "#bd93f9"
red = "#ff5555"
yellow = "#f1fa8c"

[directory]
format = " [$path]($style)"
style = "fg:purple"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
Documents = "󰈙"
Downloads = " "
Music = " "
Pictures = " "

[fill]
style = "fg:overlay"
symbol = " "

[git_branch]
format = "on [$symbol $branch]($style) "
style = "fg:comment"
symbol = ""

[git_status]
style = "fg:comment"
format = '[$all_status$ahead_behind]($style) '
disabled = true

[time]
disabled = false
format = "[$time ]($style) "
tyle = "fg:rose"
time_format = "%I:%M%P"
use_12hr = true

[username]
disabled = false
format = "[󰣇 $user]($style)"
show_always = true
style_root = "fg:iris"
style_user = "fg:iris"

# Languages

[c]
style = "fg:pine"
format = "[$symbol$version]($style) "
disabled = false
symbol = " "

[elixir]
style = "fg:pine"
format = "[](fg:overlay)[$symbol$version]($style)[](fg:overlay) "
disabled = false
symbol = " "

[elm]
style = "fg:pine"
format = "[](fg:overlay)[$symbol$version]($style)[](fg:overlay) "
disabled = false
symbol = " "

[golang]
style = "fg:pine"
format = "[](fg:overlay)[$symbol$version]($style)[](fg:overlay) "
disabled = false
symbol = " "

[haskell]
style = "fg:pine"
format = "[](fg:overlay)[$symbol$version]($style)[](fg:overlay) "
disabled = false
symbol = " "

[java]
style = "fg:pine"
format = "[](fg:overlay)[$symbol$version]($style)[](fg:overlay) "
disabled = false
symbol = " "

[julia]
style = "fg:pine"
format = "[](fg:overlay)[$symbol$version]($style)[](fg:overlay) "
disabled = false
symbol = " "

[nodejs]
style = "fg:pine"
format = "[](fg:overlay)[$symbol$version]($style)[](fg:overlay) "
disabled = false
symbol = "󰎙 "

[nim]
style = "fg:pine"
format = "[](fg:overlay)[$symbol$version]($style)[](fg:overlay) "
disabled = false
symbol = "󰆥 "

[rust]
style = "fg:pine"
format = "[](fg:overlay)[$symbol$version]($style)[](fg:overlay) "
disabled = false
symbol = ""

[scala]
style = "fg:pine"
format = "[](fg:overlay)[$symbol$version]($style)[](fg:overlay) "
disabled = false
symbol = " "

[python]
style = "fg:purple"
format = "[$symbol$version]($style) "
disabled = false
symbol = ' '
