format = """
$directory \
$git_branch \
$git_status \
$fill \
$c \
$elixir \
$elm \
$golang \
$haskell \
$java \
$julia \
$nodejs \
$nim \
$rust \
$scala \
$python\n  \
[󱞪 ](fg:iris)
"""

palette = "catppuccin_mocha"

[palettes.catppuccin_mocha]
rosewater = "#f5e0dc"
flamingo = "#f2cdcd"
pink = "#f5c2e7"
mauve = "#cba6f7"
red = "#f38ba8"
maroon = "#eba0ac"
peach = "#fab387"
yellow = "#f9e2af"
green = "#a6e3a1"
teal = "#94e2d5"
sky = "#89dceb"
sapphire = "#74c7ec"
blue = "#89b4fa"
lavender = "#b4befe"
text = "#cdd6f4"
subtext1 = "#bac2de"
subtext0 = "#a6adc8"
overlay2 = "#9399b2"
overlay1 = "#7f849c"
overlay0 = "#6c7086"
surface2 = "#585b70"
surface1 = "#45475a"
surface0 = "#313244"
base = "#1e1e2e"
mantle = "#181825"
crust = "#11111b"

[directory]
format = " [$path]($style)"
style = "fg:mauve"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
Documents = "󰈙"
Downloads = " "
Music = " "
Pictures = " "

[fill]
style = "fg:overlay"
symbol = " "

[git_branch]
format = "on [$symbol $branch]($style) "
style = "fg:teal"
symbol = ""

[git_status]
style = "fg:comment"
format = '[$all_status$ahead_behind]($style) '
disabled = true

[time]
disabled = false
format = "[$time ]($style) "
tyle = "fg:rose"
time_format = "%I:%M%P"
use_12hr = true

[username]
disabled = false
format = "[󰣇 $user]($style)"
show_always = true
style_root = "fg:iris"
style_user = "fg:iris"

# Languages

[c]
style = "fg:pine"
format = "[$symbol$version]($style) "
disabled = false
symbol = " "

[elixir]
style = "fg:pine"
format = "[](fg:overlay)[$symbol$version]($style)[](fg:overlay) "
disabled = false
symbol = " "

[elm]
style = "fg:pine"
format = "[](fg:overlay)[$symbol$version]($style)[](fg:overlay) "
disabled = false
symbol = " "

[golang]
style = "fg:pine"
format = "[](fg:overlay)[$symbol$version]($style)[](fg:overlay) "
disabled = false
symbol = " "

[haskell]
style = "fg:pine"
format = "[](fg:overlay)[$symbol$version]($style)[](fg:overlay) "
disabled = false
symbol = " "

[java]
style = "fg:pine"
format = "[](fg:overlay)[$symbol$version]($style)[](fg:overlay) "
disabled = false
symbol = " "

[julia]
style = "fg:pine"
format = "[](fg:overlay)[$symbol$version]($style)[](fg:overlay) "
disabled = false
symbol = " "

[nodejs]
style = "fg:pine"
format = "[](fg:overlay)[$symbol$version]($style)[](fg:overlay) "
disabled = false
symbol = "󰎙 "

[nim]
style = "fg:pine"
format = "[](fg:overlay)[$symbol$version]($style)[](fg:overlay) "
disabled = false
symbol = "󰆥 "

[rust]
style = "fg:pine"
format = "[](fg:overlay)[$symbol$version]($style)[](fg:overlay) "
disabled = false
symbol = ""

[scala]
style = "fg:pine"
format = "[](fg:overlay)[$symbol$version]($style)[](fg:overlay) "
disabled = false
symbol = " "

[python]
style = "fg:peach"
format = "[$symbol$version]($style) "
disabled = false
symbol = ' '
